//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.34003
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFSresources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EFSlanguage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EFSlanguage() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EFSresources.EFSlanguage", typeof(EFSlanguage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ladezeit der Anwendung ähnelt.
        /// </summary>
        public static string DicAppLoadTime {
            get {
                return ResourceManager.GetString("DicAppLoadTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Billion ähnelt.
        /// </summary>
        public static string DicBillion {
            get {
                return ResourceManager.GetString("DicBillion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Billionstel ähnelt.
        /// </summary>
        public static string DicBillionth {
            get {
                return ResourceManager.GetString("DicBillionth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Entwickler ähnelt.
        /// </summary>
        public static string DicCompany {
            get {
                return ResourceManager.GetString("DicCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Aktueller RAM-Verbrauch ähnelt.
        /// </summary>
        public static string DicCurrentRamUsage {
            get {
                return ResourceManager.GetString("DicCurrentRamUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die E-Mail ähnelt.
        /// </summary>
        public static string DicEmail {
            get {
                return ResourceManager.GetString("DicEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hundert ähnelt.
        /// </summary>
        public static string DicHundert {
            get {
                return ResourceManager.GetString("DicHundert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hundertstel ähnelt.
        /// </summary>
        public static string DicHundredth {
            get {
                return ResourceManager.GetString("DicHundredth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Letzte Aktualisierung ähnelt.
        /// </summary>
        public static string DicLastUpdate {
            get {
                return ResourceManager.GetString("DicLastUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zugesicherter RAM-Verbrauch ähnelt.
        /// </summary>
        public static string DicMaxRamUsage {
            get {
                return ResourceManager.GetString("DicMaxRamUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Milliard ähnelt.
        /// </summary>
        public static string DicMilliard {
            get {
                return ResourceManager.GetString("DicMilliard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Milliardstel ähnelt.
        /// </summary>
        public static string DicMilliardth {
            get {
                return ResourceManager.GetString("DicMilliardth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Million ähnelt.
        /// </summary>
        public static string DicMillion {
            get {
                return ResourceManager.GetString("DicMillion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Millionstel ähnelt.
        /// </summary>
        public static string DicMillionth {
            get {
                return ResourceManager.GetString("DicMillionth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Höchster RAM-Verbrauch ähnelt.
        /// </summary>
        public static string DicPeakRamUsage {
            get {
                return ResourceManager.GetString("DicPeakRamUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Billiarde ähnelt.
        /// </summary>
        public static string DicQuadrillion {
            get {
                return ResourceManager.GetString("DicQuadrillion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Billiardstel ähnelt.
        /// </summary>
        public static string DicQuadrillionth {
            get {
                return ResourceManager.GetString("DicQuadrillionth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Trillion ähnelt.
        /// </summary>
        public static string DicQuintillion {
            get {
                return ResourceManager.GetString("DicQuintillion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Trillionstel ähnelt.
        /// </summary>
        public static string DicQuintillionth {
            get {
                return ResourceManager.GetString("DicQuintillionth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bewertung abgeben ähnelt.
        /// </summary>
        public static string DicRateReview {
            get {
                return ResourceManager.GetString("DicRateReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Aktualisieren ähnelt.
        /// </summary>
        public static string DicRefresh {
            get {
                return ResourceManager.GetString("DicRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Absenden ähnelt.
        /// </summary>
        public static string DicSendOff {
            get {
                return ResourceManager.GetString("DicSendOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Support ähnelt.
        /// </summary>
        public static string DicSupport {
            get {
                return ResourceManager.GetString("DicSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zehn ähnelt.
        /// </summary>
        public static string DicTen {
            get {
                return ResourceManager.GetString("DicTen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zehntel ähnelt.
        /// </summary>
        public static string DicTenth {
            get {
                return ResourceManager.GetString("DicTenth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tausend ähnelt.
        /// </summary>
        public static string DicThousand {
            get {
                return ResourceManager.GetString("DicThousand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tausendstel ähnelt.
        /// </summary>
        public static string DicThousandth {
            get {
                return ResourceManager.GetString("DicThousandth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Version ähnelt.
        /// </summary>
        public static string DicVersion {
            get {
                return ResourceManager.GetString("DicVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hilfe ähnelt.
        /// </summary>
        public static string EFShelpViewTitle {
            get {
                return ResourceManager.GetString("EFShelpViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Über ähnelt.
        /// </summary>
        public static string EFSinfoView_About {
            get {
                return ResourceManager.GetString("EFSinfoView_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Impressum ähnelt.
        /// </summary>
        public static string EFSinfoView_Credits {
            get {
                return ResourceManager.GetString("EFSinfoView_Credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Leistungsdiagnose ähnelt.
        /// </summary>
        public static string EFSinfoView_Diagnostic {
            get {
                return ResourceManager.GetString("EFSinfoView_Diagnostic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Feedback ähnelt.
        /// </summary>
        public static string EFSinfoView_Feedback {
            get {
                return ResourceManager.GetString("EFSinfoView_Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Versionen ähnelt.
        /// </summary>
        public static string EFSinfoView_History {
            get {
                return ResourceManager.GetString("EFSinfoView_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zusatz ähnelt.
        /// </summary>
        public static string EFSlogsystem_Addition {
            get {
                return ResourceManager.GetString("EFSlogsystem_Addition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Klasse ähnelt.
        /// </summary>
        public static string EFSlogsystem_Class {
            get {
                return ResourceManager.GetString("EFSlogsystem_Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Inhalt ähnelt.
        /// </summary>
        public static string EFSlogsystem_Content {
            get {
                return ResourceManager.GetString("EFSlogsystem_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Level ähnelt.
        /// </summary>
        public static string EFSlogsystem_LogLevel {
            get {
                return ResourceManager.GetString("EFSlogsystem_LogLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Logs ähnelt.
        /// </summary>
        public static string EFSlogsystem_LogViewTitle {
            get {
                return ResourceManager.GetString("EFSlogsystem_LogViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bei der letzten Ausführung der Application kam es zu einem Absturz der Anwendung. Bitte Schicken Sie uns den Log zu, damit wir dem Fehler nachgehen können.
        ///Log jetzt zusenden? ähnelt.
        /// </summary>
        public static string EFSlogsystem_MessageBox_Content {
            get {
                return ResourceManager.GetString("EFSlogsystem_MessageBox_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Logsystem ähnelt.
        /// </summary>
        public static string EFSlogsystem_MessageBox_Header {
            get {
                return ResourceManager.GetString("EFSlogsystem_MessageBox_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zeitstempel ähnelt.
        /// </summary>
        public static string EFSlogsystem_TimeStamp {
            get {
                return ResourceManager.GetString("EFSlogsystem_TimeStamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler melden ähnelt.
        /// </summary>
        public static string FeedbackItemBug {
            get {
                return ResourceManager.GetString("FeedbackItemBug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Allgemeines ähnelt.
        /// </summary>
        public static string FeedbackItemCommon {
            get {
                return ResourceManager.GetString("FeedbackItemCommon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Erweiterung vorschlagen ähnelt.
        /// </summary>
        public static string FeedbackItemFeature {
            get {
                return ResourceManager.GetString("FeedbackItemFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Navigation fehlgeschlagen ähnelt.
        /// </summary>
        public static string PageTransporterNavigationFailed {
            get {
                return ResourceManager.GetString("PageTransporterNavigationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Möglicherweise werden vorhandene Daten auf dem Telefon überschrieben.
        ///Wollen Sie fortfahren? ähnelt.
        /// </summary>
        public static string SkyDriveDownloadOverwrite_MessageBox_Content {
            get {
                return ResourceManager.GetString("SkyDriveDownloadOverwrite_MessageBox_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Möglicherweise werden vorhandene Daten auf SkyDrive überschrieben.
        ///Wollen Sie fortfahren? ähnelt.
        /// </summary>
        public static string SkyDriveUploadOverwrite_MessageBox_Content {
            get {
                return ResourceManager.GetString("SkyDriveUploadOverwrite_MessageBox_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Angloamerikanisches System ähnelt.
        /// </summary>
        public static string UnitSystem_ImperialUK_Name {
            get {
                return ResourceManager.GetString("UnitSystem_ImperialUK_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Meile(n) ähnelt.
        /// </summary>
        public static string UnitSystem_ImperialUS_Length2_Name {
            get {
                return ResourceManager.GetString("UnitSystem_ImperialUS_Length2_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die mi ähnelt.
        /// </summary>
        public static string UnitSystem_ImperialUS_Length2_Shortcut {
            get {
                return ResourceManager.GetString("UnitSystem_ImperialUS_Length2_Shortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Imperiales US-System ähnelt.
        /// </summary>
        public static string UnitSystem_ImperialUS_Name {
            get {
                return ResourceManager.GetString("UnitSystem_ImperialUS_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gallone ähnelt.
        /// </summary>
        public static string UnitSystem_ImperialUS_Volume2_Name {
            get {
                return ResourceManager.GetString("UnitSystem_ImperialUS_Volume2_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die gal ähnelt.
        /// </summary>
        public static string UnitSystem_ImperialUS_Volume2_Shortcut {
            get {
                return ResourceManager.GetString("UnitSystem_ImperialUS_Volume2_Shortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kilometer ähnelt.
        /// </summary>
        public static string UnitSystem_Metrical_Length2_Name {
            get {
                return ResourceManager.GetString("UnitSystem_Metrical_Length2_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die km ähnelt.
        /// </summary>
        public static string UnitSystem_Metrical_Length2_Shortcut {
            get {
                return ResourceManager.GetString("UnitSystem_Metrical_Length2_Shortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Metrisches System ähnelt.
        /// </summary>
        public static string UnitSystem_Metrical_Name {
            get {
                return ResourceManager.GetString("UnitSystem_Metrical_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Liter ähnelt.
        /// </summary>
        public static string UnitSystem_Metrical_Volume2_Name {
            get {
                return ResourceManager.GetString("UnitSystem_Metrical_Volume2_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die l ähnelt.
        /// </summary>
        public static string UnitSystem_Metrical_Volume2_Shortcut {
            get {
                return ResourceManager.GetString("UnitSystem_Metrical_Volume2_Shortcut", resourceCulture);
            }
        }
    }
}
