//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.34003
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TankManager.Lokalisierung {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Translation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translation() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TankManager.Lokalisierung.Translation", typeof(Translation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die EFSdeveloping ist ein Freizeitprojekt von mir, ErdnussFlipS bzw. mein richtiger Name ist Philipp. Ich studiere Informatik, weshalb ich auch nicht täglich bzw. in regelmäßigen Abständen an der Anwendung (App) arbeiten kann. ähnelt.
        /// </summary>
        public static string AboutText {
            get {
                return ResourceManager.GetString("AboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Was bzw. wer steckt hinter EFSdeveloping? ähnelt.
        /// </summary>
        public static string AboutText_Header {
            get {
                return ResourceManager.GetString("AboutText_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Durchschnittsverbrauch ähnelt.
        /// </summary>
        public static string DicAverageFuelConsumption {
            get {
                return ResourceManager.GetString("DicAverageFuelConsumption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rechnungsbetrag ähnelt.
        /// </summary>
        public static string DicBillValue {
            get {
                return ResourceManager.GetString("DicBillValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rechnungs-betrag ähnelt.
        /// </summary>
        public static string DicBillValueBreak {
            get {
                return ResourceManager.GetString("DicBillValueBreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kanister ähnelt.
        /// </summary>
        public static string DicCanister {
            get {
                return ResourceManager.GetString("DicCanister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Verbinden ähnelt.
        /// </summary>
        public static string DicConnect {
            get {
                return ResourceManager.GetString("DicConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Verbunden ähnelt.
        /// </summary>
        public static string DicConnected {
            get {
                return ResourceManager.GetString("DicConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Verbrauch ähnelt.
        /// </summary>
        public static string DicConsuption {
            get {
                return ResourceManager.GetString("DicConsuption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Verbrauch auf 100km ähnelt.
        /// </summary>
        public static string DicConsuptionAverage {
            get {
                return ResourceManager.GetString("DicConsuptionAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Erstellt ähnelt.
        /// </summary>
        public static string DicCreated {
            get {
                return ResourceManager.GetString("DicCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Datum ähnelt.
        /// </summary>
        public static string DicDate {
            get {
                return ResourceManager.GetString("DicDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Löschen ähnelt.
        /// </summary>
        public static string DicDelete {
            get {
                return ResourceManager.GetString("DicDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Entwicklung ähnelt.
        /// </summary>
        public static string DicDeveloper {
            get {
                return ResourceManager.GetString("DicDeveloper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Trennen ähnelt.
        /// </summary>
        public static string DicDisconnect {
            get {
                return ResourceManager.GetString("DicDisconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Distanz ähnelt.
        /// </summary>
        public static string DicDistance {
            get {
                return ResourceManager.GetString("DicDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ändern ähnelt.
        /// </summary>
        public static string DicEdit {
            get {
                return ResourceManager.GetString("DicEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die E-Mail ähnelt.
        /// </summary>
        public static string DicEmail {
            get {
                return ResourceManager.GetString("DicEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vollgetankt ähnelt.
        /// </summary>
        public static string DicFilledUp {
            get {
                return ResourceManager.GetString("DicFilledUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Voll-getankt ähnelt.
        /// </summary>
        public static string DicFilledUpBreak {
            get {
                return ResourceManager.GetString("DicFilledUpBreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vom ähnelt.
        /// </summary>
        public static string DicFrom {
            get {
                return ResourceManager.GetString("DicFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Spritmenge ähnelt.
        /// </summary>
        public static string DicFueled {
            get {
                return ResourceManager.GetString("DicFueled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gesamtzahl an Tankvorgängen ähnelt.
        /// </summary>
        public static string DicFuelHistoryCount {
            get {
                return ResourceManager.GetString("DicFuelHistoryCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vollbetankung ähnelt.
        /// </summary>
        public static string DicFullyFuelling {
            get {
                return ResourceManager.GetString("DicFullyFuelling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kraftstoffart ähnelt.
        /// </summary>
        public static string DicGasType {
            get {
                return ResourceManager.GetString("DicGasType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Höchster Verbrauch ähnelt.
        /// </summary>
        public static string DicHighestConsuption {
            get {
                return ResourceManager.GetString("DicHighestConsuption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Aktualisiert ähnelt.
        /// </summary>
        public static string DicLastUpdate {
            get {
                return ResourceManager.GetString("DicLastUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Berechtigung ähnelt.
        /// </summary>
        public static string DicLegitimation {
            get {
                return ResourceManager.GetString("DicLegitimation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kennzeichen ähnelt.
        /// </summary>
        public static string DicLicensePlate {
            get {
                return ResourceManager.GetString("DicLicensePlate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Niedrigster Verbrauch ähnelt.
        /// </summary>
        public static string DicLowestConsuption {
            get {
                return ResourceManager.GetString("DicLowestConsuption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die insgesamt getankte Liter ähnelt.
        /// </summary>
        public static string DicMaxLiter {
            get {
                return ResourceManager.GetString("DicMaxLiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
        /// </summary>
        public static string DicName {
            get {
                return ResourceManager.GetString("DicName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Weiter ähnelt.
        /// </summary>
        public static string DicNext {
            get {
                return ResourceManager.GetString("DicNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Keine Internetverbindung ähnelt.
        /// </summary>
        public static string DicNoInternetConnection {
            get {
                return ResourceManager.GetString("DicNoInternetConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zapfsäule ähnelt.
        /// </summary>
        public static string DicPetrolPump {
            get {
                return ResourceManager.GetString("DicPetrolPump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bewertung abgeben ähnelt.
        /// </summary>
        public static string DicRateReview {
            get {
                return ResourceManager.GetString("DicRateReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Aktualisieren ähnelt.
        /// </summary>
        public static string DicRefresh {
            get {
                return ResourceManager.GetString("DicRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Speichern ähnelt.
        /// </summary>
        public static string DicSave {
            get {
                return ResourceManager.GetString("DicSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Absenden ähnelt.
        /// </summary>
        public static string DicSendOff {
            get {
                return ResourceManager.GetString("DicSendOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Support ähnelt.
        /// </summary>
        public static string DicSupport {
            get {
                return ResourceManager.GetString("DicSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bis ähnelt.
        /// </summary>
        public static string DicTo {
            get {
                return ResourceManager.GetString("DicTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gesamtkosten ähnelt.
        /// </summary>
        public static string DicTotalCosts {
            get {
                return ResourceManager.GetString("DicTotalCosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Version ähnelt.
        /// </summary>
        public static string DicVersion {
            get {
                return ResourceManager.GetString("DicVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sie sind eingeloggt. ähnelt.
        /// </summary>
        public static string EinstellungenViewBackupConnectInfo {
            get {
                return ResourceManager.GetString("EinstellungenViewBackupConnectInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hier können Sie die Daten der Anwendung, d.h. Ihre gesamten Fahrzeuge, Einstellungen, etc. in Ihrem SkyDrive sichern und von dort auch wiederherstellen. ähnelt.
        /// </summary>
        public static string EinstellungenViewBackupInfo {
            get {
                return ResourceManager.GetString("EinstellungenViewBackupInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Von SkyDrive wiederherstellen ähnelt.
        /// </summary>
        public static string EinstellungenViewBackupLoadFromSkyDrive {
            get {
                return ResourceManager.GetString("EinstellungenViewBackupLoadFromSkyDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Auf SkyDrive sichern ähnelt.
        /// </summary>
        public static string EinstellungenViewBackupSaveToSkyDrive {
            get {
                return ResourceManager.GetString("EinstellungenViewBackupSaveToSkyDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fahrzeuge ähnelt.
        /// </summary>
        public static string EinstellungenViewCarManagePivotTitle {
            get {
                return ResourceManager.GetString("EinstellungenViewCarManagePivotTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Allgemein ähnelt.
        /// </summary>
        public static string EinstellungenViewGeneralPivotTitle {
            get {
                return ResourceManager.GetString("EinstellungenViewGeneralPivotTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zuletzt gesichert am ähnelt.
        /// </summary>
        public static string EinstellungenViewLastBackup {
            get {
                return ResourceManager.GetString("EinstellungenViewLastBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kilometerzähler beim Tanken ähnelt.
        /// </summary>
        public static string EinstellungenViewLengthCounter {
            get {
                return ResourceManager.GetString("EinstellungenViewLengthCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vor dem Beenden fragen ähnelt.
        /// </summary>
        public static string EinstellungenViewShowExitMessage {
            get {
                return ResourceManager.GetString("EinstellungenViewShowExitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fahrzeug Beabeiten-Button ähnelt.
        /// </summary>
        public static string EinstellungenViewShowVehicleEditButton_Header {
            get {
                return ResourceManager.GetString("EinstellungenViewShowVehicleEditButton_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es wird ein Button neben dem Fahrzeugkennzeichen in der Übersicht angezeigt. ähnelt.
        /// </summary>
        public static string EinstellungenViewShowVehicleEditButton_Info {
            get {
                return ResourceManager.GetString("EinstellungenViewShowVehicleEditButton_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Software-Logs anzeigen ähnelt.
        /// </summary>
        public static string EintellungenViewLogEntry {
            get {
                return ResourceManager.GetString("EintellungenViewLogEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Automatisch ähnelt.
        /// </summary>
        public static string EnumKilometerzaeherAutomatic {
            get {
                return ResourceManager.GetString("EnumKilometerzaeherAutomatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Individuell ähnelt.
        /// </summary>
        public static string EnumKilometerzaeherIndividual {
            get {
                return ResourceManager.GetString("EnumKilometerzaeherIndividual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tageskilometer als Zähler ähnelt.
        /// </summary>
        public static string FahrzeugAddViewCounterText {
            get {
                return ResourceManager.GetString("FahrzeugAddViewCounterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Extras ähnelt.
        /// </summary>
        public static string FahrzeugAddViewPivotExtras {
            get {
                return ResourceManager.GetString("FahrzeugAddViewPivotExtras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Allgemein ähnelt.
        /// </summary>
        public static string FahrzeugAddViewPivotGeneral {
            get {
                return ResourceManager.GetString("FahrzeugAddViewPivotGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fahrzeug hinzufügen ähnelt.
        /// </summary>
        public static string FahrzeugAddViewTitle {
            get {
                return ResourceManager.GetString("FahrzeugAddViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fahrzeug ändern ähnelt.
        /// </summary>
        public static string FahrzeugEditViewTitle {
            get {
                return ResourceManager.GetString("FahrzeugEditViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hilfe ähnelt.
        /// </summary>
        public static string HelpViewTitle {
            get {
                return ResourceManager.GetString("HelpViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Automatisch:
        ///Beim Tanken wird automatisch der Kilometerzähler gewählt.
        ///
        ///Individuell:
        ///Beim Tanken kann man den Kilometerzähler individuell wählen. ähnelt.
        /// </summary>
        public static string InfoUCText {
            get {
                return ResourceManager.GetString("InfoUCText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Über ähnelt.
        /// </summary>
        public static string InfoViewAbout {
            get {
                return ResourceManager.GetString("InfoViewAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Impressum ähnelt.
        /// </summary>
        public static string InfoViewCredits {
            get {
                return ResourceManager.GetString("InfoViewCredits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Leistungsdiagnose ähnelt.
        /// </summary>
        public static string InfoViewDiagnostic {
            get {
                return ResourceManager.GetString("InfoViewDiagnostic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Spenden ähnelt.
        /// </summary>
        public static string InfoViewDonation {
            get {
                return ResourceManager.GetString("InfoViewDonation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Spenden Sie für den Erhalt und der Weiterentwicklung dieser Anwendung!
        ///
        ///Für den Erhalt dieser Anwendung im Windows Phone Store (Marketplace) ist jährlich eine Gebühr von 77 € nötig.
        ///
        ///Wenn Ihnen diese Anwendung gefällt, dann können Sie einen freiwilligen Betrag zur Kostendeckung leisten. Mit diesem Beitrag unterstützen Sie die zukünftige Weiterentwicklung.
        ///
        ///Klicken Sie dazu auf den Spenden-Button um über Paypal zu spenden.
        ///Sie werden automatisch zur Spendenseite weitergeleitet. ähnelt.
        /// </summary>
        public static string InfoViewDonationText {
            get {
                return ResourceManager.GetString("InfoViewDonationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Feedback ähnelt.
        /// </summary>
        public static string InfoViewFeedback {
            get {
                return ResourceManager.GetString("InfoViewFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Versionen ähnelt.
        /// </summary>
        public static string InfoViewHistory {
            get {
                return ResourceManager.GetString("InfoViewHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Informationen ähnelt.
        /// </summary>
        public static string InfoViewTitle {
            get {
                return ResourceManager.GetString("InfoViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Einstellungen ähnelt.
        /// </summary>
        public static string MainPageAppBarMenuItemSettings {
            get {
                return ResourceManager.GetString("MainPageAppBarMenuItemSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Auswertung ähnelt.
        /// </summary>
        public static string MainPageDataAnalysisPivotTitle {
            get {
                return ResourceManager.GetString("MainPageDataAnalysisPivotTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Aktuell ähnelt.
        /// </summary>
        public static string MainPageFuelLogPivotTitle {
            get {
                return ResourceManager.GetString("MainPageFuelLogPivotTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es sind keine Daten vohanden oder es ist kein Fahrzeug ausgewählt. Gehen Sie zu den Einstellungen und wählen Sie unter Fahrzeuge eines aus oder klicken Sie auf (+) um eines zu erstellen. ähnelt.
        /// </summary>
        public static string MainPageNoContentContent {
            get {
                return ResourceManager.GetString("MainPageNoContentContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kein Fahrzeug vorhanden ähnelt.
        /// </summary>
        public static string MainPageNoContentHeader {
            get {
                return ResourceManager.GetString("MainPageNoContentHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Übersicht ähnelt.
        /// </summary>
        public static string MainPageOverviewPivotTitle {
            get {
                return ResourceManager.GetString("MainPageOverviewPivotTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ein unerwarteter Fehler ist aufgetreten.
        ///Die Application wird beendet. ähnelt.
        /// </summary>
        public static string MessageBoxApplicationUnhandeldException {
            get {
                return ResourceManager.GetString("MessageBoxApplicationUnhandeldException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nicht alle Angaben sind korrekt bzw. angegeben.
        ///Bitte kontrollieren Sie folgende Elemente: ähnelt.
        /// </summary>
        public static string MessageBoxCheckDataContent {
            get {
                return ResourceManager.GetString("MessageBoxCheckDataContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sie sind dabei Ihr aktuelles Fahrzeug unwiderruflich zu löschen. Wollen Sie fortfahren? ähnelt.
        /// </summary>
        public static string MessageBoxCurrentVehicleDelContent {
            get {
                return ResourceManager.GetString("MessageBoxCurrentVehicleDelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Aktuelles Fahrzeug löschen ähnelt.
        /// </summary>
        public static string MessageBoxCurrentVehicleDelHeader {
            get {
                return ResourceManager.GetString("MessageBoxCurrentVehicleDelHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das Datum darf nicht älter sein, als das Datum des letzten Tankvorganges ähnelt.
        /// </summary>
        public static string MessageBoxDateChangedFailedContent {
            get {
                return ResourceManager.GetString("MessageBoxDateChangedFailedContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Falsches Datum ähnelt.
        /// </summary>
        public static string MessageBoxDateChangedFailedHeader {
            get {
                return ResourceManager.GetString("MessageBoxDateChangedFailedHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sie sind dabei alle Fahrzeuge unwiderruflich zu löschen.
        ///Wollen Sie fortfahren? ähnelt.
        /// </summary>
        public static string MessageBoxDeleteAllVehiclesContent {
            get {
                return ResourceManager.GetString("MessageBoxDeleteAllVehiclesContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Alle Fahrzeuge löschen ähnelt.
        /// </summary>
        public static string MessageBoxDeleteAllVehiclesHeader {
            get {
                return ResourceManager.GetString("MessageBoxDeleteAllVehiclesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sie sind dabei Ihr gesamtes Tankbuch für das Fahrzeug mit dem Kennzeichen {0} ({1}) unwiderruflich zu löschen. Sofern Sie kein Backup auf SkyDrive haben, können Sie das nicht rückgängig machen. Es gehen alle Statistiken für dieses Fahrzeug verloren!
        ///Wollen Sie wirklich fortfahren? ähnelt.
        /// </summary>
        public static string MessageBoxDeleteCompleteFuellog_Content {
            get {
                return ResourceManager.GetString("MessageBoxDeleteCompleteFuellog_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tankbuch löschen (Achtung!) ähnelt.
        /// </summary>
        public static string MessageBoxDeleteCompleteFuellog_Header {
            get {
                return ResourceManager.GetString("MessageBoxDeleteCompleteFuellog_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sie sind dabei den Tankvorgang vom {0} ({1}) zu löschen.
        ///Wollen Sie forfahren? ähnelt.
        /// </summary>
        public static string MessageBoxDeleteRefueling_Content {
            get {
                return ResourceManager.GetString("MessageBoxDeleteRefueling_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tankvorgang löschen ähnelt.
        /// </summary>
        public static string MessageBoxDeleteRefueling_Header {
            get {
                return ResourceManager.GetString("MessageBoxDeleteRefueling_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sie sind dabei den letzten Tankvorgang vom {0} ({1}) zu löschen.
        ///Wollen Sie forfahren? ähnelt.
        /// </summary>
        public static string MessageBoxDeleteRefuelingLastOne_Content {
            get {
                return ResourceManager.GetString("MessageBoxDeleteRefuelingLastOne_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Letzten Tankvorgang löschen ähnelt.
        /// </summary>
        public static string MessageBoxDeleteRefuelingLastOne_Header {
            get {
                return ResourceManager.GetString("MessageBoxDeleteRefuelingLastOne_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wollen Sie die Anwendung wirklich beenden? ähnelt.
        /// </summary>
        public static string MessageBoxExit_Content {
            get {
                return ResourceManager.GetString("MessageBoxExit_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Anwendung beenden ähnelt.
        /// </summary>
        public static string MessageBoxExit_Header {
            get {
                return ResourceManager.GetString("MessageBoxExit_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Da Sie zum ersten Mal tanken, muss bei diesem Tankvorgang die Gesamtkilometerzahl angegeben werden. ähnelt.
        /// </summary>
        public static string MessageBoxFirstFuellingContent {
            get {
                return ResourceManager.GetString("MessageBoxFirstFuellingContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das erste Mal Tanken ähnelt.
        /// </summary>
        public static string MessageBoxFirstFuellingHeader {
            get {
                return ResourceManager.GetString("MessageBoxFirstFuellingHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es konnte keine Verbindung zu den Live-Diensten hergestellt werden. ähnelt.
        /// </summary>
        public static string MessageBoxLiveConnectFailed1Content {
            get {
                return ResourceManager.GetString("MessageBoxLiveConnectFailed1Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es konnte keine Verbindung zu den Live-Diensten hergestellt werden.
        ///Mögliche Gründe:
        ///{0} ähnelt.
        /// </summary>
        public static string MessageBoxLiveConnectFailed1ContentReason {
            get {
                return ResourceManager.GetString("MessageBoxLiveConnectFailed1ContentReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es ist ein Fehler bei der Anmeldung aufgetreten. ähnelt.
        /// </summary>
        public static string MessageBoxLiveConnectFailed2Content {
            get {
                return ResourceManager.GetString("MessageBoxLiveConnectFailed2Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es ist ein Fehler in der Live API aufgetreten.
        ///Bitte Entschuldigen Sie dies. ähnelt.
        /// </summary>
        public static string MessageBoxLiveConnectFailed3Content {
            get {
                return ResourceManager.GetString("MessageBoxLiveConnectFailed3Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Keine Internetverbindung vorhanden ähnelt.
        /// </summary>
        public static string MessageBoxLiveConnectFailedReasonNoConnection {
            get {
                return ResourceManager.GetString("MessageBoxLiveConnectFailedReasonNoConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Application hat keine Rechte enthalten ähnelt.
        /// </summary>
        public static string MessageBoxLiveConnectFailedReasonUserGranting {
            get {
                return ResourceManager.GetString("MessageBoxLiveConnectFailedReasonUserGranting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das letzte Mal wurde nur eine Teilbetankung durchgeführt. Um den Verbrauch richtig berechnen zu können wird der Gesamtkilometerstand benötigt. ähnelt.
        /// </summary>
        public static string MessageBoxNeedTotalKmContent {
            get {
                return ResourceManager.GetString("MessageBoxNeedTotalKmContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gesamtkilometerstand benötigt ähnelt.
        /// </summary>
        public static string MessageBoxNeedTotalKmHeader {
            get {
                return ResourceManager.GetString("MessageBoxNeedTotalKmHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ihre Daten konnten nicht auf SkyDrive gesichert werden.
        ///Möglicherweise bestand keine Internetverbindung, versuchen Sie es bei bestehender Internetverbindung erneut.
        ///Bei wiederholtem auftreten und bestehender Internetverbindung setzten Sie sich bitte mit uns in Verbindung. ähnelt.
        /// </summary>
        public static string MessageBoxSkyDriveBackupFailed {
            get {
                return ResourceManager.GetString("MessageBoxSkyDriveBackupFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ihre Daten wurden auf SkyDrive gesichert. ähnelt.
        /// </summary>
        public static string MessageBoxSkyDriveBackupSuccess {
            get {
                return ResourceManager.GetString("MessageBoxSkyDriveBackupSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es ist ein Fehler beim herunterladen Ihrer Sicherung aufgetreten. ähnelt.
        /// </summary>
        public static string MessageBoxSkyDriveRestoreFailed {
            get {
                return ResourceManager.GetString("MessageBoxSkyDriveRestoreFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es ist ein Fehler bei der Wiederherstellung aufgetreten.
        ///Auf Ihrem SkyDrive ist kein Backup vorhanden. ähnelt.
        /// </summary>
        public static string MessageBoxSkyDriveRestoreFailedNotExist {
            get {
                return ResourceManager.GetString("MessageBoxSkyDriveRestoreFailedNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sind Sie sicher, dass Sie Ihre lokalen Daten mit dem SkyDrive Backup überschreiben wollen?
        ///Ihre aktuellen Daten gehen verloren! ähnelt.
        /// </summary>
        public static string MessageBoxSkyDriveRestoreLegitimate {
            get {
                return ResourceManager.GetString("MessageBoxSkyDriveRestoreLegitimate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ihre Daten wurden von SkyDrive wiederhergestellt. ähnelt.
        /// </summary>
        public static string MessageBoxSkyDriveRestoreSuccess {
            get {
                return ResourceManager.GetString("MessageBoxSkyDriveRestoreSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das Datum muss gleich oder unter dem {0} sein. ähnelt.
        /// </summary>
        public static string MessageBoxTankbuchViewDTPickerFrom {
            get {
                return ResourceManager.GetString("MessageBoxTankbuchViewDTPickerFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das Datum muss gleich oder über dem {0} sein. ähnelt.
        /// </summary>
        public static string MessageBoxTankbuchViewDTPickerTo {
            get {
                return ResourceManager.GetString("MessageBoxTankbuchViewDTPickerTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das Datum muss zwischen dem vorherigen und nachfolgenden Tankvorgang liegen. ähnelt.
        /// </summary>
        public static string MessageBoxTankenEditViewDateTimeFault_Content {
            get {
                return ResourceManager.GetString("MessageBoxTankenEditViewDateTimeFault_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Falsche Datumsangabe ähnelt.
        /// </summary>
        public static string MessageBoxTankenEditViewDateTimeFault_Header {
            get {
                return ResourceManager.GetString("MessageBoxTankenEditViewDateTimeFault_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} ausgewählt ähnelt.
        /// </summary>
        public static string MessageBoxVehicleChangedContent {
            get {
                return ResourceManager.GetString("MessageBoxVehicleChangedContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fahrzeug gewechselt ähnelt.
        /// </summary>
        public static string MessageBoxVehicleChangedHeader {
            get {
                return ResourceManager.GetString("MessageBoxVehicleChangedHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} wurde gelöscht ähnelt.
        /// </summary>
        public static string MessageBoxVehicleDelContent {
            get {
                return ResourceManager.GetString("MessageBoxVehicleDelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fahrzeug gelöscht ähnelt.
        /// </summary>
        public static string MessageBoxVehicleDelHeader {
            get {
                return ResourceManager.GetString("MessageBoxVehicleDelHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Alle Einträge löschen ähnelt.
        /// </summary>
        public static string TankbuchViewDeleteAll {
            get {
                return ResourceManager.GetString("TankbuchViewDeleteAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fügen Sie durch Klicken auf das Tanksäulen-Symbol Tankvorgänge hinzu. ähnelt.
        /// </summary>
        public static string TankbuchViewNoContent_Content {
            get {
                return ResourceManager.GetString("TankbuchViewNoContent_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Keine Daten vorhanden ähnelt.
        /// </summary>
        public static string TankbuchViewNoContent_Header {
            get {
                return ResourceManager.GetString("TankbuchViewNoContent_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tankbuch ähnelt.
        /// </summary>
        public static string TankbuchViewTitle {
            get {
                return ResourceManager.GetString("TankbuchViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tanken ähnelt.
        /// </summary>
        public static string TankenAddViewTitle {
            get {
                return ResourceManager.GetString("TankenAddViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tankvorgang ändern ähnelt.
        /// </summary>
        public static string TankenEditViewTitle {
            get {
                return ResourceManager.GetString("TankenEditViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tankbuchübersicht ähnelt.
        /// </summary>
        public static string TanktabelleViewTitle {
            get {
                return ResourceManager.GetString("TanktabelleViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nein ähnelt.
        /// </summary>
        public static string ToggleSwitchNo {
            get {
                return ResourceManager.GetString("ToggleSwitchNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Aus ähnelt.
        /// </summary>
        public static string ToggleSwitchOff {
            get {
                return ResourceManager.GetString("ToggleSwitchOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An ähnelt.
        /// </summary>
        public static string ToggleSwitchOn {
            get {
                return ResourceManager.GetString("ToggleSwitchOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ja ähnelt.
        /// </summary>
        public static string ToggleSwitchYes {
            get {
                return ResourceManager.GetString("ToggleSwitchYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die l/100 km ähnelt.
        /// </summary>
        public static string UnitSystemConsuption {
            get {
                return ResourceManager.GetString("UnitSystemConsuption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tageskilometerstand ähnelt.
        /// </summary>
        public static string UnitSystemDriveLength {
            get {
                return ResourceManager.GetString("UnitSystemDriveLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gesamtkilometerstand ähnelt.
        /// </summary>
        public static string UnitSystemDriveTotalLength {
            get {
                return ResourceManager.GetString("UnitSystemDriveTotalLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tachostand ähnelt.
        /// </summary>
        public static string UnitSystemDriveTotalLengthBreak {
            get {
                return ResourceManager.GetString("UnitSystemDriveTotalLengthBreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kilometer ähnelt.
        /// </summary>
        public static string UnitSystemLength {
            get {
                return ResourceManager.GetString("UnitSystemLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die km ähnelt.
        /// </summary>
        public static string UnitSystemLengthShort {
            get {
                return ResourceManager.GetString("UnitSystemLengthShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Grad Celsius ähnelt.
        /// </summary>
        public static string UnitSystemTemperature {
            get {
                return ResourceManager.GetString("UnitSystemTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die °C ähnelt.
        /// </summary>
        public static string UnitSystemTemperatureShort {
            get {
                return ResourceManager.GetString("UnitSystemTemperatureShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Spritmenge ähnelt.
        /// </summary>
        public static string UnitSystemVolume {
            get {
                return ResourceManager.GetString("UnitSystemVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die l ähnelt.
        /// </summary>
        public static string UnitSystemVolumeShort {
            get {
                return ResourceManager.GetString("UnitSystemVolumeShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Versionsgeschichte anzeigen? ähnelt.
        /// </summary>
        public static string UpgradeContent {
            get {
                return ResourceManager.GetString("UpgradeContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Anwendung aktualisiert ähnelt.
        /// </summary>
        public static string UpgradeTitle {
            get {
                return ResourceManager.GetString("UpgradeTitle", resourceCulture);
            }
        }
    }
}
